version: "3"

services:
 app:
  image: mageinferno/magento2-nginx
  links:
   - php-fpm
  working_dir: /src/
  environment:
   - VIRTUAL_HOST=m4.mohtshm.com
  volumes:
   - data_share:/src/pub/
  networks:
   - php_net
   - default

 php-fpm:
  image: mageinferno/magento2-php
  volumes:
   - data_share:/src/pub/
  networks:
   - php_net


volumes:
 data_share:
  driver: local
  driver_opts:
   type: volume
   device: /var/development/src/
   o: bind

networks:
 php_net:
  driver: bridge
  ipam:
   driver: default
   config:
   -
     subnet: 10.10.3.0/24
 default:
  external:
   name: dockercompose_local-app-net
