# from Markoshust 
# Mage Inferno Docker Compose (https://github.com/mageinferno/magento2-docker-compose)
# Version 7.0.0

version: "3"

services:
  app:
    image: mageinferno/magento2-nginx:1.11-1
    links:
      - m5db
      - m5phpfpm
    volumes: &appvolumes
      - appdata:/var/www/html
    environment:
      - VIRTUAL_HOST=m5.mohtshm.com
      - PHP_HOST=m5phpfpm
      - PHP_PORT=9000

  m5phpfpm:
    image: mageinferno/magento2-php:7.0-fpm-1
    links:
      - m5db
    volumes: *appvolumes
    environment:
      - PHP_MEMORY_LIMIT=512M
      - PHP_HOST=m5phpfpm
      - PHP_PORT=9000

  m5db:
    image: percona:5.7
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 8001:3306
    env_file: env/mysql.env

  setup:
    image: mageinferno/magento2-php:7.0-fpm-1
    command: /usr/local/bin/mage-setup
    links:
      - m5db
    volumes: *appvolumes
    env_file: env/setup.env

volumes:
  dbdata:
  appdata:

networks:
 default:
  external:
   name: magento2dockercomposemaster_www
